### ISSUE TITLE
Geonet Event quakeml Conversion: No SI units, No "units" file display for amplitudes

### ISSUE THREAD

**Issue by salichon** [GeoNet/seiscompml-to-quakeml#3]
See https://github.com/GeoNet/help/issues/60

Conversion from sc3xml to quakeml differ 
 - Geonet produced events quakeml may benefit from improvements in the events parameter information as spotted by Callum-Chamberlain (see https://github.com/GeoNet/help/issues/60)

[Geonet_2019p498440.quakeml.txt](https://github.com/GeoNet/seiscompml-to-quakeml/files/3603043/Geonet_2019p498440.quakeml.txt)
[Sc3_2019p49440.quakeml.txt](https://github.com/GeoNet/seiscompml-to-quakeml/files/3603044/Sc3_2019p49440.quakeml.txt)

FYI @quiffman @GeoNet/dmc-admins

**Comment by calum-chamberlain** [comment]
Any chance methodID can be populated as well, with URLs to the correct page in the seiscomp docs for how the processing is undertaken.  e.g. this would help with things like the issue raised in [Help issue 58](https://github.com/GeoNet/help/issues/58). The response to that issue from Fabian at the QuakeML team was:

> An Amplitude element can reference a Pick object but need not. It was quite difficult to come up with a general concept of amplitude description because amplitude measurements can be quite 
different. Regarding time information there is the timeInterval attribute, which describes a time interval, and one point in time within that interval that has a special emphasis. The semantics, however, is method-dependent and cannot be specified in a general way. You have the methodID attribute which can hold a URI. This should be populated with a resource identifier providing more information on the method used, e.g., a publication DOI, or a http web resource.

**Comment by salichon** [comment]
Is accounted for into https://github.com/GeoNet/tickets/issues/5259
